name: Feature request
description: Propón una mejora o nueva capacidad
title: "[FEAT] "
labels: ["feat"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Resumen
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Alcance
    validations:
      required: true
  - type: textarea
    id: success
    attributes:
      label: Criterio de éxito
    validations:
      required: true
